events { worker_connections 1024; }

http {
    map $http_x_forwarded_for $client_ip {
        ""      $remote_addr;
        "~^(?P<first_ip>[^,]+)" $first_ip;
        default $http_x_forwarded_for;
    }

    log_format json_analytics escape=json '{'
        '"ip": "$client_ip",'
        '"timestamp": "$time_iso8601",'
        '"method": "$request_method",'
        '"uri": "$request_uri",'
        '"status": $status,'
        '"payload_size": $request_length,'
        '"user_agent": "$http_user_agent"'
    '}';

    access_log /var/log/nginx/access.log json_analytics;

    include /etc/nginx/blocked_ips.conf;

    server {
        listen 80;
        location / {
            proxy_pass         http://target-app:5000;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $client_ip;
            proxy_set_header   X-Forwarded-For   $client_ip;

            # Required for SSE streams
            proxy_buffering    off;
            proxy_cache        off;
            proxy_read_timeout 3600s;
        }
    }
}
